vitejs/docs-de

docs/guide/migration.md

docs(migration): tweak wordings (#14876)

---

docs/guide/env-and-mode.md

        docs(env): add .env parsing note and vite-env.d.ts augmentation

---

docs/guide/ssr.md

        docs(ssr): add a missing closing parenthesis

---

docs/guide/features.md

        docs: fix lightning css typo

---

docs/guide/features.md
packages/vite/src/node/plugins/importMetaGlob.ts
packages/vite/types/importGlob.d.ts
playground/glob-import/index.html
playground/worker/worker/main-module.js

        feat(glob-import): deprecate as option

---

docs/config/server-options.md
packages/vite/src/node/watch.ts

        fix(hmr): make watcher ignore build.outDir

---

docs/guide/performance.md

        docs: add tip on browser extensions to perf guide

---

.gitignore
docs/guide/migration.md

        fix(deps): update all non-major dependencies

---

docs/guide/api-plugin.md

feat: support multiple HMR clients on the server (#15340)

---

docs/guide/index.md

docs: changed `bunx create-vite` to `bun create vite`

---

docs/config/shared-options.md

        (docs)perf: use thread for preprocessors (#143)

---

docs/guide/features.md

(docs) add warning on Worker import with constructor limitations

---

docs/config/dep-optimization-options.md

(docs) feat(optimizer): holdUntilCrawlEnd option (#147)

---

docs/config/server-options.md

        docs: update proxy option link

---

docs/config/dep-optimization-options.md
docs/config/shared-options.md

docs: add feedback discussion links for experimental features

---

docs/guide/cli.md

refactor: remove `vite build --force`

---

docs/guide/performance.md

docs: add not about disabling the cache to the performance guide (#176)

---

docs/guide/features.md

 docs(features): clarify sentences about JSX usage (#179)

---

docs/config/dep-optimization-options.md

docs: improve optimizeDeps.esbuildOptions type (#180)

---

docs/config/dep-optimization-options.md

chore: lint (#181)

---

docs/config/dep-optimization-options.md

chore: prettier dep optimization (#182)

---

docs/guide/ssr.md

 refactor(runtime): minor tweaks (#196)

---

docs/_data/team.js

        docs: complete team social links

---

docs/guide/api-hmr.md
docs/guide/api-plugin.md

        docs(hmr): improve handleHotUpdate and add further reading

---

docs/config/server-options.md

docs(hmr): document `hmr.protocol` setting
